### ISSUE TITLE
Works with the normal image boxes, but not with image boxes created by extensions

### ISSUE THREAD

**Issue by HWiese1980** [klimaleksus/stable-diffusion-webui-fix-image-paste#1]
I've tried this extension on my A1111 installation and it works with the image boxes that come with it. But it does not work with image boxes created by extensions like https://github.com/Mikubill/sd-webui-controlnet. Can you take a look into this issue please? I'm looking for exactly this functionality, but for all image boxes in A1111.

**Comment by aleksusklim** [comment]
This extension was made specifically for that ControlNet actually: https://github.com/Mikubill/sd-webui-controlnet/issues/76

Can you double-check, pressing "X" in the corner of the input (if it is there), then moving your mouse to the side of the input so that the pointer is not touching the helper text – and then press Ctrl+V ?

If this will success, then it's working as intended.

**Comment by HWiese1980** [comment]
Ah perfect. Yes, that works. Didn't know where exactly to place the cursor. 

Thank you very much!
